version: '3.4'

volumes:
  django-gen:
  django-socket:
  postgres-data:

services:
  django:
    build: "."
    environment:
      - DJANGO_DEBUG
      - DJANGO_PUBLIC_HOSTNAME
      - DJANGO_SECRET_KEY
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - "./django:/usr/src/django"
      - "django-socket:/var/www/uwsgi"
      - "django-gen:/gen"

  nginx:
    image: nginx:1.18.0
    ports:
      - "${LISTEN_NGINX_HTTP}:80"
    restart: unless-stopped
    volumes:
      - "django-gen:/var/www/static:ro"
      - "django-socket:/var/www/uwsgi"
      - "./nginx/${NGINX_CONFIG}:/etc/nginx/conf.d/default.conf:ro"

  postgres:
    image: postgres:13.1
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    restart: unless-stopped
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./postgres_files:/postgres_files"
